name: Tests

on: [push, pull_request]

jobs:
  test:
    env:
      DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}
    runs-on: ${{ matrix.os || 'ubuntu-latest' }}
    strategy:
      fail-fast: false
      max-parallel: 6
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11']
        include:
          - python-version: 3.6
            os: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.dev.txt

    - name: Run tox tests
      run: |
        # run tests with coverage
        tox

    - name: Upload coverage to Codecov
      if: ${{ matrix.python-version == '3.11' }}
      uses: codecov/codecov-action@v1

    - name: Report test-coverage to DeepSource
      if: ${{ matrix.python-version == '3.11' }}
      run: |
        # Install the CLI
        curl https://deepsource.io/cli | sh
        # Send the report to DeepSource
        ./bin/deepsource report --analyzer test-coverage --key python --value-file coverage.xml
